### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by interlan** [jbogdani/BraDyCMS#4]
Win XP SP3, wamp local server. Latest release from github.
Installation showed the success page, then on trying to login I get a blank page.
error log file is : 
[17-Sep-2013 10:53:15 UTC] PHP Notice:  Use of undefined constant self - assumed 'self' in E:__misccms\bradycms\lib\Autoloader.inc on line 13

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined index: timezone in E:__misccms\bradycms\lib\cfg.inc on line 37

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined index: prefix in E:__misccms\bradycms\lib\cfg.inc on line 37

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined index: default_lang in E:__misccms\bradycms\lib\cfg.inc on line 37

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined index: db_connection in E:__misccms\bradycms\lib\cfg.inc on line 37

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined index: db_connection in E:__misccms\bradycms\lib\cfg.inc on line 37

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined index: user_confirmed in E:__misccms\bradycms\admin.php on line 37

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined variable: stop_error in E:__misccms\bradycms\admin.php on line 42

[17-Sep-2013 10:53:15 UTC] PHP Notice:  Undefined index: user_confirmed in E:__misccms\bradycms\admin.php on line 49

[17-Sep-2013 10:53:15 UTC] PHP Warning:  parse_ini_file(version): failed to open stream: No such file or directory in E:__misccms\bradycms\lib\version.inc on line 13

[17-Sep-2013 10:53:15 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'File `version` can not be parsed E:__misccms\bradycms\lib\version.inc, 16' in E:__misccms\bradycms\lib\version.inc:16
Stack trace:
#0 E:__misccms\bradycms\lib\version.inc(31): version::parse()
#1 E:__misccms\bradycms\modules\admin\admin.php(13): version::current()
#2 E:__misccms\bradycms\admin.php(51): admin_ctrl->showLoginForm()
#3 {main}

  thrown in E:__misccms\bradycms\lib\version.inc on line 16

PS. Wouldn't it be better to use MySql?

Regards

Petros

**Comment by Emanuele20** [comment]
Hello! Having the same issue...try to install in a directory (http://www.myweb/urcms) mod the second line or .htaccess /urcms or writing the complete path like up....and always open my original start page www.myweb.....what i miss?
Kindly Regards
Emanuele

**Comment by jbogdani** [comment]
Hello @Emanuele20,
are you running apache on windows? Do you have mod_rewrite enabled?

**Comment by Emanuele20** [comment]
hi! i'm using hosting linux and tested .htaccess mod_rewrite is available...

**Comment by jbogdani** [comment]
If the installation folder is `urcms`, and if it is a subfolder of the localhost root directory, then the starting part (first two lines) of your `.htaccess` file should be:

    RewriteEngine on
    RewriteBase /urcms/

Your directory tree should be:

[web root]
|-- urcms
|----|--bower_components
|----|--css
|----|--docs
|----|--{etc...}
|----|--.gitmodules
|----|--.htaccess
|----|--LICENSE
|----|--{etc...}

You should point your browser at `http://{your root we directory, es: localhost}/urcms` and it should work.

**Comment by Emanuele20** [comment]
trying re-uploading all with that change...and nothing open always my index...about my available mod_write .htaccess i ve found here a simple test and return positive....in another project i've created a 404 page with .htaccess i know that is another thing....but....really dont know....

**Comment by jbogdani** [comment]
@Emanuele20 you could drop me a line at develop@bradypus.net and I'll try to help.
I'm not sure what issue you are running through.
